version: "3.8"
services:
  client:
    build: ./client
    container_name: client_c    
    ports:
      - "3000:3000"    
    volumes:
      - ./client:/app
      - ./app/node_modules
    networks:
    - mern-app
    stdin_open: true
    tty: true

  api:
    build: ./api
    container_name: api_c
    ports:
     - '8800:8800'
    volumes:
     - ./api:/app
     - ./app/node_modules
    depends_on:
      - mongo
    networks:
      - mern-app
      
  mongo: 
    image: mongo
    container_name: mongo_c    
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local